name: League & Scoring Settings Request
description: Submit your league and scoring settings to generate a custom configuration.
body:
  - type: input
    id: league_name
    attributes:
      label: League Name
      description: What is the name of your fantasy league?
      placeholder: "My Fantasy League"
    validations:
      required: true

  - type: input
    id: number_of_teams
    attributes:
      label: Number of Teams
      description: How many teams are in your league?
      placeholder: "12"
    validations:
      required: true

  - type: markdown
    attributes:
      value: |
        ### Roster Settings (number per team)
  - type: input
    id: qb
    attributes:
      label: QB
      placeholder: "1"
    validations: { required: true }
  - type: input
    id: rb
    attributes:
      label: RB
      placeholder: "2"
    validations: { required: true }
  - type: input
    id: wr
    attributes:
      label: WR
      placeholder: "2"
    validations: { required: true }
  - type: input
    id: te
    attributes:
      label: TE
      placeholder: "1"
    validations: { required: true }
  - type: input
    id: flex
    attributes:
      label: FLEX
      placeholder: "1"
    validations: { required: false }
  - type: input
    id: k
    attributes:
      label: K
      placeholder: "1"
    validations: { required: false }
  - type: input
    id: def
    attributes:
      label: DEF
      placeholder: "1"
    validations: { required: false }
  - type: input
    id: bench
    attributes:
      label: BN (Bench)
      placeholder: "6"
    validations: { required: true }

  - type: markdown
    attributes:
      value: |
        ### Scoring Settings (enter numbers only)
  - type: input
    id: pass_yds
    attributes:
      label: Pass Yards (per yard)
      placeholder: "0.04"
    validations: { required: true }
  - type: input
    id: pass_td
    attributes:
      label: Pass TD
      placeholder: "4"
    validations: { required: true }
  - type: input
    id: int
    attributes:
      label: INT (Interception)
      placeholder: "-2"
    validations: { required: true }
  - type: input
    id: rush_yds
    attributes:
      label: Rush Yards (per yard)
      placeholder: "0.1"
    validations: { required: true }
  - type: input
    id: rush_td
    attributes:
      label: Rush TD
      placeholder: "6"
    validations: { required: true }
  - type: input
    id: rec_yds
    attributes:
      label: Rec Yards (per yard)
      placeholder: "0.1"
    validations: { required: true }
  - type: input
    id: rec_td
    attributes:
      label: Rec TD
      placeholder: "6"
    validations: { required: true }
  - type: input
    id: rec
    attributes:
      label: Receptions (PPR)
      placeholder: "1"
    validations: { required: true }

  - type: textarea
    id: additional_rules
    attributes:
      label: Additional Rules/Notes
      description: Any special rules, bonuses, or settings not covered above?
      placeholder: "E.g., Bonus for 100+ yard games, negative points for missed field goals, etc."
    validations:
      required: false
